### PR TITLE
New Home Page

### PR DESCRIPTION
**Pull request by forsythetony**
It's nowhere near ready to be merged in with the rest of the code but I just wanted to make a pull request so that I could have a place to put questions/what you guys think.

### CODE REVIEW

**Comment by forsythetony** [comment]
Eventually the number inside the circle graph won't be a percentage but rather a simple count of how many colleges match the criteria. And everything else still needs a lot of work.

**Comment by maurahoward** [comment]
Ahh you got the circle feature to work -- that's awesome!!

**Comment by maurahoward** [comment]
Also, side note, I had a Strat Comm career fair today and as part of my portfolio I included a few parts of the storyboard and showed it to agency recruiters. Everyone was really really impressed with the idea and interface, so kudos to us!

**Comment by forsythetony** [comment]
It doesn't yet work with real data. I've just got a random number hardcoded in there but eventually it should work with real data and be able to update as the user modifies the filters. And that's awesome haha. Always nice to hear.

**Comment by forsythetony** [comment]
So this is where it's at now.

New Home Page

**Comment by forsythetony** [comment]
The locations don't do anything at the moment but in the future adding a location would trim down the number of results based on the distance to that location.

**Comment by forsythetony** [comment]
So here's what the home screen looks like

screen shot 2014-02-18 at 8 25 02 am

screen shot 2014-02-18 at 8 25 14 am

**Comment by forsythetony** [comment]
This is what bookmarking looks like

bookmarking

**Comment by forsythetony** [comment]
And here's what comparing looks like (while I was messing with things I must have broken the comparison animation but that shouldn't be too difficult to fix)

comparing

**Comment by maurahoward** [comment]
So do you swipe it left to bookmark and right to compare? Also, I love those new icons! The compare one especially looks beautiful.

Could you make that filters bar the same coral color though? And then I still think the side panel needs work. 

Attached are two mock-ups I've been working on. I really want to redo the details page and use more graphs. Again, I don't mean to throw work at you or whatever, but I figured these mock ups don't hurt! 

details compare
results

**Comment by maurahoward** [comment]
And then I still plan on playing with the fonts, colors and layout. I just have been really busy this last week with my career fair/job hunting, work, etc. I'm hoping things will slow down soon though and I should have more time within the next week.

**Comment by forsythetony** [comment]
Throw as much work at me as you want as long as you're not setting due dates haha. Yea I can change the color. Do you think you could give me a color scheme of like 3 to 5 colors to use including their RGB values? Also should I go ahead and merge this into master?

**Comment by forsythetony** [comment]
And you swipe right to compare, swipe left to bookmark. I could also put both buttons on the right or left side.

**Comment by forsythetony** [comment]
Also I think we shouldn't be setting the background color for the status bar.

**Comment by JMV2112** [comment]
I Personally like both buttons on one side, that’s my own opinion though.

On Feb 18, 2014, at 1:26 PM, forsythetony <notifications@github.com<mailto:notifications@github.com>> wrote:

And you swipe right to compare, swipe left to bookmark. I could also put both buttons on the right or left side.

**Comment by forsythetony** [comment]
Here's what it looks like now

screen shot 2014-02-18 at 1 31 43 pm

**Comment by forsythetony** [comment]
I had changed it to that charcoal color because I can't get the color to be exactly the coral color the rest of the app uses because I'm only able to modify the navigation bar's tint, not a backgroundColor property. It just bugged me how it was almost like the other coral but not exactly.

**Comment by forsythetony** [comment]
Here's the code with the status bar color override commented out

``` objectivec

[application setStatusBarStyle:UIStatusBarStyleLightContent];

    /*
    if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 7) {
        [application setStatusBarStyle:UIStatusBarStyleDefault];
        self.window.clipsToBounds =YES;
        self.window.frame =  CGRectMake(0,20,self.window.frame.size.width,self.window.frame.size.height-20);

        //Added on 19th Sep 2013
        self.window.bounds = CGRectMake(0, 20, self.window.frame.size.width, self.window.frame.size.height);
        background = [[UIWindow alloc] initWithFrame: CGRectMake(0, 0, self.window.frame.size.width, 20)];
        background.backgroundColor =[UIColor customCoralColor];
        [background setHidden:NO];
    }
    */
```

Which looks like this

screen shot 2014-02-18 at 1 35 50 pm

Or with the default status bar style

``` objective-c
[application setStatusBarStyle:UIStatusBarStyleDefault];
```

screen shot 2014-02-18 at 1 41 10 pm

**Comment by maurahoward** [comment]
What do you mean by setting the background color for the status bar? Are you talking about how the triangle and the status bar are the same color? If so, I get what you're saying with that, but I also like the boldness the coral color gives to the screen. I would be open to exploring other options though.

And then for school type, could you make it look like more of a multiple choice question when you get a chance? I feel like that would be more consistent with the page design. 

And then if we have the option to do this, I think a high-quality photo with the name of our app would be nice for the loading screen. 

homescreen filters

**Pull request closed without merging**
