### PR TITLE
New Graphs

### PR DESCRIPTION
**Pull request by forsythetony**
Replaces the current graphs in the project with graphs from the [PNChart](https://github.com/kevinzhow/PNChart) project. Currently the bar graphs look like this. This should make it easier to compare multiple colleges.

### CODE REVIEW

**Comment by forsythetony** [comment]
Currently it looks like this. 
screen shot 2014-02-01 at 7 09 56 pm

**Comment by maurahoward** [comment]
I like the way PNChart looks! This isn't on the latest code though, is it?

**Comment by forsythetony** [comment]
You should be able to pull down this branch and have what you're seeing here.

**Comment by maurahoward** [comment]
At the top where it says "daily, monthly, yearly," with those nice little buttons, that would be a good way to make our "in state" "out of state" "by women" "by men" etc. look on our graphs.

screen shot 2014-02-04 at 12 40 49 pm

**Comment by forsythetony** [comment]
Is it cool if I merge it into master now?

**Comment by maurahoward** [comment]
Yes!

**Pull request merged**
