### PR TITLE
Panel View Navigation

### PR DESCRIPTION
**Pull request by forsythetony**
Adds the ability to navigate through the app using a panel view accessible either through a bar button item in the navigation bar or by swiping to the right.

image

### CODE REVIEW

**Comment by forsythetony** [comment]
Added some random icons just to see how it would look. 

image

**Comment by forsythetony** [comment]
There's now a sync button in the panel view. Click the button once to start it and again to stop it. In the future this would be set up to start spinning when the request for updated data is sent and stop when it's received. 

image

**Comment by maurahoward** [comment]
I like this idea ... It would take away the tab bar design problem I've been having and would also leave room for additional features.  Is this feature in the latest version of the code?

**Comment by JMV2112** [comment]
Yea it's on the latest commit. Just pull and you'll have it.

**Comment by maurahoward** [comment]
If we do the panel view navigation, I want it to look like this. I think the panel view should be on the right side so we don't lose our back button. 

And then the two major things having this feature changes is the compare feature on the results page and the bookmark button on the details page.

For the compare feature, I'm thinking we use the swipe gesture to select colleges to compare instead of what we have now. And then I'm still unsure of where to put the bookmark button on the details page. Suggestions are welcome.

screen shot 2014-01-12 at 11 05 50 pm
screen shot 2014-01-12 at 11 06 00 pm

**Comment by JMV2112** [comment]
This is something we should discuss as a team in a face to face meeting this week when everyone is in town.

**Comment by JMV2112** [comment]
In my opinion it sounds like a good idea since it will interfere with the back button. I have an app (for android) that has the menu as the right navigation bar button item and it looks really nice so it does sound like a good idea to me.

**Comment by tyten** [comment]
IIDeckView is a decent 3rd party library for implementing that.

Tyten

**Comment by forsythetony** [comment]
I just downloaded it but I'm a bit confused on how to implement it and the example is done using only .xibs so I'll probably be in the first NSCoder the week of 1/19.

**Pull request merged**
